### ISSUE TITLE
Not as expected, the fish shell

### ISSUE THREAD

**Issue by Niba-nazar** [netspective-labs/home-polyglot#1]
Hi,

After Polyglot setup in Windows Debian WSL2, the Fish shell prompt does not appear as intended.

![image](https://user-images.githubusercontent.com/114569256/215108728-1bd61f15-fabb-4265-8e87-51ce29740e17.png)

**Comment by shah** [comment]
@Niba-nazar this is probably because the default Fish shell version is expected to be 3.6+. The default Fish version for Debian and Ubuntu are older (and insecure) so please upgrade using:

```bash
sudo add-apt-repository ppa:fish-shell/release-3
sudo apt-get update
sudo apt-get install fish
```

Or, you can just rebuild your VM using the latest code that I committed.
